// src/utils/aiTutor.ts
import type { GameState, AIHint } from "../types/chess";

/**
 * All hints are generated by the GPT-powered backend.
 * No more local rule engine – always high quality :)
 */
export async function generateHint(gameState: GameState): Promise<AIHint> {
  const response = await fetch("http://localhost:3001/api/hint", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ gameState }),
  });

  if (!response.ok) {
    throw new Error("Failed to fetch hint from server");
  }

  const data = await response.json();

  return {
    suggestion: data.suggestion ?? "No suggestion available.",
    explanation: data.explanation ?? "The AI could not generate an explanation.",
    // if your AIHint type has optional fields like recommendedMove, leave them undefined
  };
}
